"""add_phase_3_trust_markers

Revision ID: e8a661eec56f
Revises: 7cc76b883018
Create Date: 2026-01-02 15:05:13.161718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8a661eec56f'
down_revision: Union[str, Sequence[str], None] = '7cc76b883018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_downloads_download_status'), table_name='document_downloads')
    op.drop_index(op.f('ix_document_downloads_project_id'), table_name='document_downloads')
    op.drop_table('document_downloads')
    op.drop_index(op.f('ix_document_extractions_document_id'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_document_type'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_processor_name'), table_name='document_extractions')
    op.drop_index(op.f('ix_document_extractions_project_id'), table_name='document_extractions')
    op.drop_table('document_extractions')
    op.drop_table('ai_scores')
    op.drop_table('document_types')
    op.alter_column('bank_accounts', 'authorized_signatories',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('ix_landmarks_city'), table_name='landmarks')
    op.drop_index(op.f('ix_landmarks_is_active'), table_name='landmarks')
    op.alter_column('localities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('localities_slug_key'), 'localities', type_='unique')
    op.create_unique_constraint('uq_localities_slug', 'localities', ['slug'])
    op.alter_column('project_amenity_stats', 'onsite_details',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_project_amenity_stats_project_radius'), table_name='project_amenity_stats')
    op.drop_column('project_amenity_stats', 'count_within_radius')
    op.drop_column('project_amenity_stats', 'nearest_distance_km')
    op.alter_column('project_artifacts', 'floor_plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Structured room dimensions and layout data',
               existing_nullable=True)
    op.drop_column('project_artifacts', 'document_type_id')
    op.alter_column('project_embeddings', 'embedding_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Vector embedding as JSON array',
               existing_nullable=True)
    op.alter_column('project_embeddings', 'text_content',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Source text used for embedding',
               existing_nullable=True)
    op.alter_column('project_embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Embedding model used',
               existing_nullable=True)
    op.alter_column('project_imputations', 'imputed_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment=None,
               existing_comment='Key-value pairs of imputed fields',
               existing_nullable=True)
    op.alter_column('project_imputations', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Algorithm used',
               existing_nullable=True)
    op.alter_column('project_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('project_locations', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('project_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_project_locations_active_lat_lon'), table_name='project_locations', postgresql_where='is_active')
    op.alter_column('project_scores', 'score_status_reason',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('project_scores', 'structured_ratings',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_project_scores_amenity_score'), table_name='project_scores')
    op.drop_index(op.f('ix_project_scores_location_score'), table_name='project_scores')
    op.drop_index(op.f('ix_project_scores_overall_score'), table_name='project_scores')
    op.drop_index(op.f('ix_project_scores_score_status'), table_name='project_scores')
    op.drop_column('project_unit_types', 'club_membership_fee')
    op.drop_column('project_unit_types', 'common_area_sqft')
    op.drop_column('project_unit_types', 'open_parking_price')
    op.drop_column('project_unit_types', 'covered_parking_price')
    op.drop_column('project_unit_types', 'terrace_area_sqft')
    op.drop_column('project_unit_types', 'balcony_area_sqft')
    op.add_column('projects', sa.Column('rera_status', sa.String(length=32), server_default='ACTIVE', nullable=True))
    op.add_column('projects', sa.Column('construction_completion_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('projects', sa.Column('last_financial_audit_date', sa.Date(), nullable=True))
    op.alter_column('projects', 'qa_flags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('projects', 'has_litigation',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_projects_district'), table_name='projects')
    op.drop_index(op.f('ix_projects_has_litigation'), table_name='projects')
    op.drop_index(op.f('ix_projects_locality_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_registration_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_tehsil'), table_name='projects')
    op.drop_constraint(op.f('projects_latest_ai_score_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'localities', ['locality_id'], ['id'], ondelete='SET NULL')
    op.drop_column('projects', 'latest_ai_score_id')
    op.drop_column('projects', 'formatted_address')
    op.add_column('rera_filings', sa.Column('is_certified', sa.Boolean(), nullable=False))
    op.add_column('rera_filings', sa.Column('financial_summary', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_rera_verifications_is_current'), table_name='rera_verifications')
    op.drop_index(op.f('ix_tags_is_featured'), table_name='tags')
    op.create_foreign_key(None, 'transaction_history', 'units', ['unit_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_history', type_='foreignkey')
    op.create_index(op.f('ix_tags_is_featured'), 'tags', ['is_featured'], unique=False)
    op.create_index(op.f('ix_rera_verifications_is_current'), 'rera_verifications', ['is_current'], unique=False)
    op.drop_column('rera_filings', 'financial_summary')
    op.drop_column('rera_filings', 'is_certified')
    op.add_column('projects', sa.Column('formatted_address', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('latest_ai_score_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_latest_ai_score_id_fkey'), 'projects', 'ai_scores', ['latest_ai_score_id'], ['id'])
    op.create_index(op.f('ix_projects_tehsil'), 'projects', ['tehsil'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_index(op.f('ix_projects_registration_date'), 'projects', ['approved_date'], unique=False)
    op.create_index(op.f('ix_projects_locality_id'), 'projects', ['locality_id'], unique=False)
    op.create_index(op.f('ix_projects_has_litigation'), 'projects', ['has_litigation'], unique=False)
    op.create_index(op.f('ix_projects_district'), 'projects', ['district'], unique=False)
    op.alter_column('projects', 'has_litigation',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('projects', 'qa_flags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('projects', 'last_financial_audit_date')
    op.drop_column('projects', 'construction_completion_percent')
    op.drop_column('projects', 'rera_status')
    op.add_column('project_unit_types', sa.Column('balcony_area_sqft', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('project_unit_types', sa.Column('terrace_area_sqft', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('project_unit_types', sa.Column('covered_parking_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('project_unit_types', sa.Column('open_parking_price', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('project_unit_types', sa.Column('common_area_sqft', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('project_unit_types', sa.Column('club_membership_fee', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_project_scores_score_status'), 'project_scores', ['score_status'], unique=False)
    op.create_index(op.f('ix_project_scores_overall_score'), 'project_scores', ['overall_score'], unique=False)
    op.create_index(op.f('ix_project_scores_location_score'), 'project_scores', ['location_score'], unique=False)
    op.create_index(op.f('ix_project_scores_amenity_score'), 'project_scores', ['amenity_score'], unique=False)
    op.alter_column('project_scores', 'structured_ratings',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('project_scores', 'score_status_reason',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_project_locations_active_lat_lon'), 'project_locations', ['lat', 'lon'], unique=False, postgresql_where='is_active')
    op.alter_column('project_locations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('project_locations', 'meta_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('project_locations', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('project_imputations', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Algorithm used',
               existing_nullable=True)
    op.alter_column('project_imputations', 'imputed_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Key-value pairs of imputed fields',
               existing_nullable=True)
    op.alter_column('project_embeddings', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Embedding model used',
               existing_nullable=True)
    op.alter_column('project_embeddings', 'text_content',
               existing_type=sa.TEXT(),
               comment='Source text used for embedding',
               existing_nullable=True)
    op.alter_column('project_embeddings', 'embedding_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Vector embedding as JSON array',
               existing_nullable=True)
    op.add_column('project_artifacts', sa.Column('document_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('project_artifacts', 'floor_plan_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Structured room dimensions and layout data',
               existing_nullable=True)
    op.add_column('project_amenity_stats', sa.Column('nearest_distance_km', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('project_amenity_stats', sa.Column('count_within_radius', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_project_amenity_stats_project_radius'), 'project_amenity_stats', ['project_id', 'radius_km'], unique=False)
    op.alter_column('project_amenity_stats', 'onsite_details',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint('uq_localities_slug', 'localities', type_='unique')
    op.create_unique_constraint(op.f('localities_slug_key'), 'localities', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('localities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_landmarks_is_active'), 'landmarks', ['is_active'], unique=False)
    op.create_index(op.f('ix_landmarks_city'), 'landmarks', ['city'], unique=False)
    op.alter_column('bank_accounts', 'authorized_signatories',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('document_types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('document_types_pkey')),
    sa.UniqueConstraint('code', name=op.f('document_types_code_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('ai_scores',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ai_scores_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('score_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('input_features', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='ai_scores_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_scores_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('document_extractions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('document_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('document_type_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('raw_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extracted_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('approval_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('approval_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('validity_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('issuing_authority', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_area_sqft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('floor_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('processor_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('processor_version', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('processing_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('warnings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], name=op.f('document_extractions_document_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('document_extractions_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_extractions_pkey')),
    sa.UniqueConstraint('project_id', 'filename', name=op.f('uq_project_filename'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_document_extractions_project_id'), 'document_extractions', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_extractions_processor_name'), 'document_extractions', ['processor_name'], unique=False)
    op.create_index(op.f('ix_document_extractions_document_type'), 'document_extractions', ['document_type'], unique=False)
    op.create_index(op.f('ix_document_extractions_document_id'), 'document_extractions', ['document_id'], unique=False)
    op.create_table('document_downloads',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('document_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('local_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('file_size_bytes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('download_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('download_error', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('retry_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['project_documents.id'], name=op.f('document_downloads_document_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('document_downloads_project_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_downloads_pkey'))
    )
    op.create_index(op.f('ix_document_downloads_project_id'), 'document_downloads', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_downloads_download_status'), 'document_downloads', ['download_status'], unique=False)
    # ### end Alembic commands ###
